---
- name: Launch EC2 instance in AWS
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml  # Include the external vars file for instance parameters

  tasks:
    - name: Launch an EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        security_group: "{{ security_group_id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        wait: yes
        count: 1
        tags:
          Name: "{{ instance_name }}"
          Owner: "{{ user_email }}"
      register: ec2

    - name: Show the EC2 instance details
      debug:
        var: ec2

    - name: Set EC2 instance details as environment variables
      set_fact:
        ec2_server_name: "{{ ec2.instances[0].tags.Name }}"
        ec2_ip: "{{ ec2.instances[0].private_ip_address }}"
        ec2_instance_type: "{{ ec2.instances[0].instance_type }}"
        ec2_region: "{{ ec2.instances[0].placement.availability_zone }}"
        ec2_image: "{{ ec2.instances[0].image_id }}"
        ec2_keypair: "{{ ec2.instances[0].key_name }}"

    - name: Print EC2 Provisioning Details
      debug:
        msg: |
          Server Name: {{ ec2_server_name }}
          IP: {{ ec2_ip }}
          Instance Type: {{ ec2_instance_type }}
          Region: {{ ec2_region }}
          Image: {{ ec2_image }}
          KeyPair: {{ ec2_keypair }}
